Repository Automattic/companion, pull requests merged in 2020-06, with the labels that each got.

#38 Check if running on cli before doing anything related to auto login
  companion.php
Labels: bug

#39 Rearrange and restyle the connection banner info
  companion.php
Labels: [type] Janitorial

#41 Add Development mode to the options page
  companion.php
Labels: [Status] Ready to Merge, enhancement
